-- Bảng stories
create table stories (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text check (char_length(title) > 0),
  created_at timestamptz default now()
);

-- Bảng questions
create table questions (
  id bigint generated by default as identity primary key,
  story_id bigint references stories not null,
  question_text text not null,
  video_url text, -- URL đến video trên R2
  created_at timestamptz default now()
);

-- Bật Row Level Security
alter table stories enable row level security;
alter table questions enable row level security;

-- Tạo Policies để user chỉ thấy được dữ liệu của mình
create policy "Users can view their own stories." on stories for select using (auth.uid() = user_id);
create policy "Users can insert their own stories." on stories for insert with check (auth.uid() = user_id);
-- Thêm các policy khác cho questions...